spring:

# datasource
  datasource:
    driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:authorization
    url: jdbc:h2:file:E:\\data\\authorization;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  # jpa
  #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    #hibernate.ddl-auto: update

  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      use-new-id-generator-mappings: false

encryption:
  secret: verySecret
  salt: jozo

token:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

logging:
  level:
    root: WARN
    com:
      borio: TRACE
